### ISSUE TITLE
A guide without the heroku CLI

### ISSUE THREAD

**Issue by fonsp** [milesfrain/GenieOnHeroku#1]
Hi!

I used this sample project to create a how-to-heroku that only uses the heroku GUI. If you are interested, you could link to it, or we could use this as the README for this project?

https://gist.github.com/fonsp/38965d7595a5d1060e27d6ca2084778d

-fons

**Comment by milesfrain** [comment]
Thanks. Added your gist link to the readme.

**Comment by fonsp** [comment]
Fun!
